set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports s]
set_property PACKAGE_PIN V10 [get_ports a]
set_property PACKAGE_PIN U11 [get_ports b]
set_property PACKAGE_PIN K15 [get_ports c]
set_property PACKAGE_PIN H17 [get_ports s]
